<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Z5X-HYD-LT010" ignored="0" name="Default test" tests="32" failures="6" timestamp="2020-08-03T16:11:59 IST" time="11.712" errors="0">
  <testcase name="POST_CreateAUser_Nodes" time="3.028" classname="com.User.UserApiTests"/>
  <testcase name="POST_CreateAUser_StatusCode_Time" time="0.738" classname="com.User.UserApiTests">
    <failure type="java.lang.AssertionError" message="Time allocated 703ms is greater than expected time 500ms expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Time allocated 703ms is greater than expected time 500ms expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- POST_CreateAUser_StatusCode_Time -->
  <testcase name="POST_verifyOTP_Nodes" time="0.316" classname="com.User.UserApiTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&amp;quot;is_guest&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;full_name&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;dob&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;email&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;gender&amp;quot; node is not present in the response body expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
"is_guest" node is not present in the response body expected [true] but found [false],
"full_name" node is not present in the response body expected [true] but found [false],
"dob" node is not present in the response body expected [true] but found [false],
"email" node is not present in the response body expected [true] but found [false],
"gender" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- POST_verifyOTP_Nodes -->
  <testcase name="POST_verifyOTP_StatusCode_Time" time="0.255" classname="com.User.UserApiTests"/>
  <testcase name="GET_GetPreference_Nodes" time="0.351" classname="com.User.UserApiTests"/>
  <testcase name="GET_GetPreference_StatusCode_Time" time="0.179" classname="com.User.UserApiTests"/>
  <testcase name="GET_OtherUserProfile_Nodes" time="0.401" classname="com.User.UserApiTests"/>
  <testcase name="GET_OtherUserProfile_StatusCode_Time" time="0.395" classname="com.User.UserApiTests"/>
  <testcase name="GET_UsersFollowingMe" time="0.256" classname="com.User.UserApiTests"/>
  <testcase name="GET_UsersFollowingMe_StatusCode_Time" time="0.22" classname="com.User.UserApiTests"/>
  <testcase name="GET_getProfile_Nodes" time="0.258" classname="com.User.UserApiTests"/>
  <testcase name="GET_getProfile_StatusCode_Time" time="0.281" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdateBankDetails_Nodes" time="0.196" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdateBankDetails_StatusCode_Time" time="0.184" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdatePreference_Nodes" time="0.176" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdatePreferences_StatusCode_Time" time="0.21" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdateProfileImage_Nodes" time="0.618" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdateProfileImage_StatusCode_Time" time="0.485" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdateProfile_Nodes" time="0.23" classname="com.User.UserApiTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&amp;quot;profile_picture&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;under18&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;is_guest&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;bank_details&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;@type&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;bank_account_full_name&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;accountType&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;accountNumber&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;ifscCode&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;mobile&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;created_at&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;upi_details&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;@type&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;upi&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;user_id&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;username&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;display_language&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;full_name&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;dob&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;email&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;gender&amp;quot; node is not present in the response body expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
"profile_picture" node is not present in the response body expected [true] but found [false],
"under18" node is not present in the response body expected [true] but found [false],
"is_guest" node is not present in the response body expected [true] but found [false],
"bank_details" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false],
"bank_account_full_name" node is not present in the response body expected [true] but found [false],
"accountType" node is not present in the response body expected [true] but found [false],
"accountNumber" node is not present in the response body expected [true] but found [false],
"ifscCode" node is not present in the response body expected [true] but found [false],
"mobile" node is not present in the response body expected [true] but found [false],
"created_at" node is not present in the response body expected [true] but found [false],
"upi_details" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false],
"upi" node is not present in the response body expected [true] but found [false],
"user_id" node is not present in the response body expected [true] but found [false],
"username" node is not present in the response body expected [true] but found [false],
"display_language" node is not present in the response body expected [true] but found [false],
"full_name" node is not present in the response body expected [true] but found [false],
"dob" node is not present in the response body expected [true] but found [false],
"email" node is not present in the response body expected [true] but found [false],
"gender" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PUT_UpdateProfile_Nodes -->
  <testcase name="PUT_UpdateProfile_StatusCode_Time" time="0.373" classname="com.User.UserApiTests"/>
  <testcase name="PUT_UpdateUpiDetails_Nodes" time="0.21" classname="com.User.UserApiTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&amp;quot;upi_details&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;upi&amp;quot; node is not present in the response body expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
"upi_details" node is not present in the response body expected [true] but found [false],
"upi" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PUT_UpdateUpiDetails_Nodes -->
  <testcase name="PUT_UpdateUpiDetails_StatusCode_Time" time="0.192" classname="com.User.UserApiTests"/>
  <testcase name="GET_BankDetails_Nodes" time="0.212" classname="com.User.UserApiTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&amp;quot;bank_account_full_name&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;accountNumber&amp;quot; node is not present in the response body expected [true] but found [false],
	ifscCode node is not present in the response body expected [true] but found [false],
	accountType node is not present in the response body expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
"bank_account_full_name" node is not present in the response body expected [true] but found [false],
"accountNumber" node is not present in the response body expected [true] but found [false],
ifscCode node is not present in the response body expected [true] but found [false],
accountType node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GET_BankDetails_Nodes -->
  <testcase name="GET_BankDetails_StatusCode_Time" time="0.166" classname="com.User.UserApiTests"/>
  <testcase name="POST_DeleteBankDetails_Nodes" time="0.172" classname="com.User.UserApiTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&amp;quot;@type&amp;quot; node is not present in the response body expected [true] but found [false],
	&amp;quot;@type&amp;quot; node is not present in the response body expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
"@type" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- POST_DeleteBankDetails_Nodes -->
  <testcase name="POST_DeleteBankDetails_StatusCode_Time" time="0.21" classname="com.User.UserApiTests"/>
  <testcase name="POST_DeleteUpiDetails_Nodes" time="0.176" classname="com.User.UserApiTests"/>
  <testcase name="POST_DeleteUpiDetails_StatusCode_Time" time="0.272" classname="com.User.UserApiTests"/>
  <testcase name="POST_UnfollowUser_Nodes" time="0.174" classname="com.User.UserApiTests"/>
  <testcase name="POST_UnfollowUser_StatusCode_Time" time="0.186" classname="com.User.UserApiTests"/>
  <testcase name="POST_FollowUser_Nodes" time="0.189" classname="com.User.UserApiTests"/>
  <testcase name="POST_FollowUser_StatusCode_time" time="0.178" classname="com.User.UserApiTests"/>
</testsuite> <!-- Default test -->
